### ISSUE TITLE
SDK Bug: Xcode 11.0 (11A419c) fails to compile because of Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /~<...>/MBSDK-Example-iOS/Pods/MBMobileSDK/MBMobileSDK/MBMobileSDK.framework/Modules/MBMobileSDK.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by oaxjogi** [Daimler/MBSDK-community-support#2]
The newly released Xcode 11.0 (11A419c) cannot build the Swift sample app because MBMobileSDK has compiled with Swift 5.0.1

Steps to reproduce the behavior (for example):
1. Getting started --> https://developer.mercedes-benz.com/sdks/ios/guides/ios_getting_started
2. BUG: Build and run the project. 

 - OS: iOS
 - SDK Build Version:
Installing Alamofire (4.9.0)
Installing AlamofireImage (3.5.2)
Installing DarklyEventSource (4.0.2)
Installing JWTDecode (2.3.0)
Installing JumioMobileSDK (3.3.1)
Installing KeychainAccess (3.2.0)
Installing LaunchDarkly (3.0.4)
Installing MBCarKit (1.0.0)
Installing MBCommonKit (1.0.0)
Installing MBDeeplinkKit (1.0.0)
Installing MBIngressKit (1.0.0)
Installing MBMobileSDK (1.0.0)
Installing MBNetworkKit (1.0.0)
Installing MBRealmKit (1.0.0)
Installing MBSupportKit (1.0.0)
Installing MBUIKit (1.0.0)
Installing Realm (3.17.3)
Installing RealmSwift (3.17.3)
Installing Starscream (3.1.0)
Installing SwiftGen (6.1.0)
Installing SwiftLint (0.35.0)
Installing SwiftProtobuf (1.6.0)
Installing YandexMobileMetrica (3.7.1)

## Smartphone (please complete the following information): 
 - Device: iPad Air 3rd generation

**Comment by AF-cgi** [comment]
@oaxjogi Currently our SDK supports only Swift 4.2 and Swift 5.0.

**Comment by oaxjogi** [comment]
@AF-cgi Would be nice to be more clear on https://developer.mercedes-benz.com/sdks/ios/guides/ios_getting_started

**Comment by Ralf-Daimler** [comment]
@oaxjogi ,  @AF-cgi : Portal doku is updated , see
https://developer.mercedes-benz.com/sdks/ios/guides/ios_getting_started
