### ISSUE TITLE
Question/Feedback: <short title>Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by malengatiger** [Daimler/MBSDK-community-support#3]
## Please provide name of your project:
 <my-project>

**Comment by malengatiger** [comment]
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler . How do I resolve this?

**Comment by Ralf-Daimler** [comment]
Assigned to @robinlieb

**Comment by Ralf-Daimler** [comment]
Note: Currently our SDK supports Swift 5.0, Swift 5.1 and Swift 5.2.

Please see https://developer.mercedes-benz.com/sdks/ios/guides/ios_getting_started
